### PR TITLE
Adapt routes to new pagination feature

### LINKED ISSUE #159: Adapt routes to new pagination feature
**Describe the feature or bug**
A clear and concise description of what the bug is or what the feature accomplishes.

**If it is a bug, describe the steps to reproduce the behavior:**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or visually describe your feature.

**Additional context**

### PR DESCRIPTION
**Pull request by victorgois**
# API Routes Pagination Enhancement

## Overview
This PR implements pagination support for API routes by adding `limit` and `offset` parameters. It also standardizes the response format by accessing `response.data.results` instead of directly using `response.data`.

### API Routes Enhancement
- Added support for `limit` and `offset` URL parameters in API routes
- Example: `http://localhost:3000/api/skill?limit=5&offset=5`
- Parameters are passed through to the backend API

### Response Format Standardization
- Updated GET methods to access data via `response.data.results` instead of `response.data`
- This change ensures consistency with the backend API response structure
- Improves error handling by checking for the existence of the results property

### Service Layer Updates
- Updated service functions to support pagination parameters
- Added URL parameter construction for pagination
- Example usage:
  ```typescript
  const data = await skillService.fetchSkills({
    headers: { Authorization: `Token ${token}` },
    limit: 10,
    offset: 20
  });
  ```

### Hooks Layer Updates
- Updated hooks to receive limit and offset parameters
- Example:
```typescript
export function useUsers(limit?: number, offset?: number) {
  const { data: session } = useSession();
  const [users, setUsers] = useState<UserProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchUsers = async () => {
      if (session?.user?.id && session?.user?.token) {
        try {
          const data = await userService.fetchAllUsers(
            session.user.token,
            undefined,
            limit,
            offset
          );
          setUsers(data);
        } catch (error) {
          console.error("Error fetching users:", error);
          setError(error.message);
        } finally {
          setIsLoading(false);
        }
      }
    };

    fetchUsers();
  }, [session, limit, offset]);

  return { users, isLoading, error };
}
```

## Attention

- The route ``` /list/{list_type} ``` which is used in several components was not updated with pagination. 

## Benefits
- Enables efficient data loading for large datasets
- Reduces network payload size
- Improves application performance
- Provides better user experience with paginated content

## Related Issues
Closes #159

### CODE REVIEW

**Review by albertoleoncio — APPROVED** [review]
LGTM!

File: src/services/skillService.ts [hunk 1]
```diff
@@ -4,14 +4,34 @@ interface QueryData {
...
+      // Construir URL com parâmetros de paginação
+      let url = `/api/skill`;
+      const params = new URLSearchParams();
+
+      if (queryData.limit !== undefined) {
+        params.append("limit", queryData.limit.toString());
+      }
+
+      if (queryData.offset !== undefined) {
+        params.append("offset", queryData.offset.toString());
```
Comment (leticia-nascimento) [inline src/services/skillService.ts:23]: nao dava pra fazer só params: { limit, offset }, como os outros casos? nao entendi bem pq precisou fazer com append

File: src/app/api/users/route.ts [hunk 2]
```diff
@@ -5,21 +5,22 @@ export async function GET(request: NextRequest) {
...
+        Authorization: authHeader,
+      },
+      params: {
+        search,
+        limit,
+        offset,
+      },
+    });
+
+    return NextResponse.json(queryResponse.data.results);
```
Comment (leticia-nascimento) [inline src/app/api/users/route.ts:23]: aqui nao pode ser assim ne? tem que retornar um user só, ele vem sozinho mas dentro de um array nao?

File: src/services/skillService.ts (hunk 1 above)
Comment (victorgois) [reply src/services/skillService.ts:23]: Verdade! É que fiz esse antes dos outros e esqueci de alterar

File: src/hooks/useOrganizationProfile.ts [hunk 3]
```diff
@@ -4,7 +4,12 @@ import { useState, useCallback, useEffect, useMemo } from "react";
 import { organizationProfileService } from "@/services/organizationProfileService";
 import { Organization } from "@/types/organization";
 
-export function useOrganization(token?: string, specificOrgId?: number) {
+export function useOrganization(
+  token?: string,
+  specificOrgId?: number,
```
[the remark this answers is not in the document]
Comment (victorgois) [reply src/hooks/useOrganizationProfile.ts:9]: Então, é que no fetchOrganizations a gente passa um array de ids e a buscamos eles pelo serviço getOrganizationById. Daí, não vi muito sentido usar a paginação ali. De qualquer forma setei como parametros não obrigatorios pra se a gente precisar e for refatorar depois, usar eles.

**Review by leticia-nascimento — APPROVED** [review]

**Review by leticia-nascimento — APPROVED** [review]
